### ISSUE TITLE
cannot change hostname

### ISSUE THREAD

**Issue by pichwo** [Tinkerforge/red-brick#1]
/usr/local/scripts/settings_network_change_hostname.py fails at :

"from reconfigure.configs import HostsConfig"

resolved by :

https://pypi.python.org/packages/source/r/reconfigure/reconfigure-0.1.39.tar.gz
tar -xvzf reconfigure-0.1.39.tar.gz
cd reconfigure-0.1.39
python2 setup.py install

**Comment by borg42** [comment]
Thank you for the bug report!

We indeed forgot to add a version check for the feature, the reconfigure lib will be available in image version 1.7.

I will close this issue after the 1.7 release.

**Comment by photron** [comment]
Image 1.7 was released years ago, closing issue.
