### ISSUE TITLE
RTC datetime on red is always synchron. in UTC

### ISSUE THREAD

**Issue by Nic2012** [Tinkerforge/red-brick#2]
According to https://github.com/Tinkerforge/red-brick/tree/master/programs/rtc_time:
If y are use the RTC bricklet the 1st time to synchronize it with the red-brick then y dont expect that it will set the system time always in UTC!
A hint in comment will help non-Linux experts a bit ;)

Same case for non-Python experts, too: If y are still on a old red-brick image e.g. 1.7 y will run in an exception that rtc bricklet binding isnt existing. If y dont use Python y probably dont know the location of the delivered bindings and how to update it manually or via remote.

As a workaround I have copied latest bindings to program folder of rtc_time script :(

**Comment by photron** [comment]
This is a copy&paste error from the GPS time example. The GPS Bricklet's date/time is in UTC.

Commit 003ae128a4f8aaa64bf25037a0c082066b5a7ae4 fixed this for the RTC time example.

Now the RTC example assumes that the Real-Time Clock Bricklet's date/time is in localtime.

**Comment by Nic2012** [comment]
Thx, works fine now with localtime.
