### ISSUE TITLE
Use better filesystem fo SD cards - f2fs

### ISSUE THREAD

**Issue by miroslavbucek** [Tinkerforge/red-brick#3]
https://en.wikipedia.org/wiki/F2FS

**Comment by photron** [comment]
The RED Brick currently uses kernel version 3.5, but F2FS was added in kernel version 3.8. Therefore, we cannot use this filesystem on the RED Brick right now.

**Comment by miroslavbucek** [comment]
thanks

**Comment by photron** [comment]
Active development for the RED Brick has stopped, as the product is discontinued. Closing the issue.
